// Search Dock controller
const KEY="search-dock-v4";
const HISTORY_KEY="search-dock-history";
const DEFAULT=[{name:"Google",icon:"G",url:"https://www.google.com/search?q={query}",mode:"link"},{name:"YouTube",icon:"▶",url:"https://www.youtube.com/results?search_query={query}",mode:"link"},{name:"IMDb",icon:"IMDb",url:"https://www.imdb.com/find/?q={query}",mode:"link"},{name:"Wikipedia",icon:"W",url:"https://en.wikipedia.org/w/index.php?search={query}",mode:"wikipedia"},{name:"Apple Movies",icon:"▶",url:"https://itunes.apple.com/search?term={query}",mode:"itunes"},{name:"Open Library",icon:"B",url:"https://openlibrary.org/search?q={query}",mode:"openlibrary"},{name:"TVMaze",icon:"TV",url:"https://api.tvmaze.com/search/shows?q={query}",mode:"tvmaze"},{name:"Stack Overflow",icon:"SO",url:"https://stackoverflow.com/search?q={query}",mode:"stackoverflow"},{name:"Hacker News",icon:"HN",url:"https://hn.algolia.com/?q={query}",mode:"hackernews"},{name:"Facebook",icon:"f",url:"https://www.facebook.com/search/top?q={query}",mode:"link"},{name:"Instagram",icon:"◎",url:"https://www.instagram.com/explore/search/keyword/?q={query}",mode:"link"},{name:"Reddit",icon:"R",url:"https://www.reddit.com/search/?q={query}",mode:"link"}];
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const old=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem("search-dock-v3")||"null");let sites=old||DEFAULT.map(x=>({...x,enabled:true}));DEFAULT.forEach(d=>{if(!sites.some(s=>s.name===d.name))sites.push({...d,enabled:true})});let last=[];
function save(){localStorage.setItem(KEY,JSON.stringify(sites))}
function history(){return JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]")}
function addHistory(q){let h=history().filter(x=>x!==q);h.unshift(q);localStorage.setItem(HISTORY_KEY,JSON.stringify(h.slice(0,30)))}
async function json(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw Error();return await r.json()}finally{clearTimeout(t)}}
function fail(name){return[{source:name,icon:"!",title:"Provider unavailable",description:"The live endpoint could not be reached. Open the native search instead.",url:"https://www.google.com/search?q="+encodeURIComponent($("#query").value.trim())}]}
async function wikipedia(q){try{const d=await json("https://en.wikipedia.org/w/rest.php/v1/search/page?q="+encodeURIComponent(q)+"&limit=6");return(d.pages||[]).map(p=>({source:"Wikipedia",icon:"W",title:p.title,description:p.description||"Wikipedia result",url:"https://en.wikipedia.org/wiki/"+encodeURIComponent((p.key||p.title).replaceAll(" ","_")),image:p.thumbnail?.url||""}))}catch{return fail("Wikipedia")}}
async function itunes(q){try{const d=await json("https://itunes.apple.com/search?term="+encodeURIComponent(q)+"&entity=movie&limit=8");return(d.results||[]).map(x=>({source:"Apple Movies",icon:"▶",title:x.trackName||q,description:[x.primaryGenreName,x.releaseDate?.slice(0,10),x.shortDescription].filter(Boolean).join(" · "),url:x.trackViewUrl||"#",image:x.artworkUrl100||""}))}catch{return fail("Apple Movies")}}
async function openLibrary(q){try{const d=await json("https://openlibrary.org/search.json?q="+encodeURIComponent(q)+"&limit=8");return(d.docs||[]).map(x=>({source:"Open Library",icon:"B",title:x.title||q,description:[x.author_name?.slice(0,2).join(", "),x.first_publish_year].filter(Boolean).join(" · "),url:x.key?"https://openlibrary.org"+x.key:"https://openlibrary.org/search?q="+encodeURIComponent(q),image:x.cover_i?"https://covers.openlibrary.org/b/id/"+x.cover_i+"-M.jpg":""}))}catch{return fail("Open Library")}}
async function tvmaze(q){try{const d=await json("https://api.tvmaze.com/search/shows?q="+encodeURIComponent(q));return d.slice(0,8).map(x=>({source:"TVMaze",icon:"TV",title:x.show.name,description:[x.show.type,x.show.language,x.show.premiered,x.show.genres?.slice(0,3).join(", ")].filter(Boolean).join(" · "),url:x.show.url,image:x.show.image?.medium||""}))}catch{return fail("TVMaze")}}
async function stackoverflow(q){try{const d=await json("https://api.stackexchange.com/2.3/search/advanced?order=desc&sort=relevance&q="+encodeURIComponent(q)+"&site=stackoverflow&pagesize=8");return d.items.map(x=>({source:"Stack Overflow",icon:"SO",title:x.title,description:[x.answer_count+" answers",x.score+" score",x.tags?.slice(0,4).join(", ")].filter(Boolean).join(" · "),url:x.link}))}catch{return fail("Stack Overflow")}}
async function hackernews(q){try{const d=await json("https://hn.algolia.com/api/v1/search?query="+encodeURIComponent(q)+"&hitsPerPage=8");return d.hits.map(x=>({source:"Hacker News",icon:"HN",title:x.title||x.story_title||q,description:[x.author,x.points!=null?x.points+" points":""].filter(Boolean).join(" · "),url:x.url||"https://news.ycombinator.com/item?id="+x.objectID}))}catch{return fail("Hacker News")}}
function siteHtml(s,i){return `<div class="site ${s.enabled!==false?"selected":""}" data-i="${i}"><button class="remove" data-remove="${i}">×</button><div class="logo">${esc(s.icon||s.name[0])}</div><b>${esc(s.name)}</b><small>${s.enabled!==false?"Enabled":"Disabled"}</small></div>`}
function renderSites(){const h=sites.map(siteHtml).join("");$("#sites").innerHTML=h;$("#sitesManage")&&($("#sitesManage").innerHTML=h);document.querySelectorAll(".site").forEach(el=>el.onclick=e=>{if(e.target.matches(".remove"))return;const i=+el.dataset.i;sites[i].enabled=sites[i].enabled===false;save();renderSites()});document.querySelectorAll(".remove").forEach(b=>b.onclick=e=>{e.stopPropagation();sites.splice(+b.dataset.remove,1);save();renderSites()})}
function renderHistory(){const h=history();$("#history").innerHTML=h.length?h.map((q,i)=>`<button class="history-item" data-q="${esc(q)}"><span>${esc(q)}</span><small>Search again</small></button>`).join(""):'<div class="empty"><h3>No search history</h3><p>Your recent searches will appear here.</p></div>';document.querySelectorAll(".history-item").forEach(b=>b.onclick=()=>{$("#query").value=b.dataset.q;showView("home");search()})}
async function search(){const q=$("#query").value.trim();if(!q)return $("#query").focus();$("#status").textContent="● Searching";$("#meta").textContent="Searching…";$("#results").className="empty";$("#results").innerHTML="<div class=big>⌕</div><h3>Searching your sources…</h3><p>Fetching available live results.</p>";const active=sites.filter(s=>s.enabled!==false&&s.url.includes("{query}"));const groups=await Promise.all(active.map(s=>s.mode==="wikipedia"?wikipedia(q):s.mode==="itunes"?itunes(q):s.mode==="openlibrary"?openLibrary(q):s.mode==="tvmaze"?tvmaze(q):s.mode==="stackoverflow"?stackoverflow(q):s.mode==="hackernews"?hackernews(q):[{source:s.name,icon:s.icon,title:q,description:"Open this source to see its live search results.",url:s.url.replaceAll("{query}",encodeURIComponent(q))}]));last=groups.flat();addHistory(q);renderHistory();$("#status").textContent="● Ready";$("#meta").textContent=`${last.length} results from ${active.length} sources · “${q}”`;$("#results").className=last.length?"results":"empty";$("#results").innerHTML=last.length?last.map(r=>`<article class=card>${r.image?'<img src="'+esc(r.image)+'" alt="" loading="lazy">':""}<div class=source><span class=logo>${esc(r.icon||r.source[0])}</span>${esc(r.source)}</div><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">↗ Open Result</a></article>`).join(""):'<div class=empty><div class=big>!</div><h3>No results</h3><p>Try another search term.</p></div>';$("#openAll").disabled=!last.length}
function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$("#homeView")?.classList.toggle("hidden",v!=="home");if(v!=="home")$("#"+v+"View")?.classList.remove("hidden");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="history")renderHistory();if(v==="sites")renderSites()}
function addSite(){const name=prompt("Website name","My Website");if(!name)return;const url=prompt("Search URL (use {query})","https://example.com/search?q={query}");if(!url||!url.includes("{query}"))return alert("URL must contain {query}");sites.push({name,icon:name[0].toUpperCase(),url,mode:"link",enabled:true});save();renderSites()}
$("#search").onclick=search;$("#query").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();search()}};$("#openAll").onclick=()=>last.forEach(r=>window.open(r.url,"_blank","noopener"));$("#add").onclick=addSite;$("#add2")?.addEventListener("click",addSite);$("#clearHistory")?.addEventListener("click",()=>{localStorage.removeItem(HISTORY_KEY);renderHistory()});document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>showView(b.dataset.view));$("#theme").onclick=()=>document.body.classList.toggle("light");$("#rememberHistory")?.addEventListener("change",e=>localStorage.setItem("search-dock-remember",e.target.checked));$("#newTabs")?.addEventListener("change",e=>localStorage.setItem("search-dock-tabs",e.target.checked));renderSites();renderHistory();